apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: default
  #annotations:
    #kubernetes.civo.com/ipv4-address: "212.2.245.7"
spec:
  selector:
    app: jenkins
  type: LoadBalancer
    #loadBalancerIP: 212.2.245.7
  ports:
  - name: http-port
    port: 8080
    targetPort: 8080
